// 80 lớp COCO (cùng tập với YOLOv8n mặc định) → tiếng Việt
// Dấu "" nghĩa là bỏ qua vì không liên quan với người khiếm thị
export const COCO_VI: Record<string, string> = {
  person: "người",
  bicycle: "xe đạp",
  car: "ô tô",
  motorcycle: "xe máy",
  airplane: "máy bay",
  bus: "xe buýt",
  train: "tàu hỏa",
  truck: "xe tải",
  boat: "thuyền",
  "traffic light": "đèn giao thông",
  "fire hydrant": "trụ cứu hỏa",
  "stop sign": "biển dừng",
  "parking meter": "đồng hồ đỗ xe",
  bench: "ghế dài",
  bird: "chim",
  cat: "mèo",
  dog: "chó",
  horse: "con ngựa",
  sheep: "con cừu",
  cow: "con bò",
  elephant: "con voi",
  bear: "con gấu",
  zebra: "con ngựa vằn",
  giraffe: "con hươu cao cổ",
  backpack: "ba lô",
  umbrella: "cái ô",
  handbag: "túi xách",
  tie: "cà vạt",
  suitcase: "vali",
  frisbee: "đĩa nhựa",
  skis: "ván trượt tuyết",
  snowboard: "ván trượt",
  "sports ball": "quả bóng",
  kite: "diều",
  "baseball bat": "gậy bóng chày",
  "baseball glove": "găng bóng chày",
  skateboard: "ván trượt",
  surfboard: "ván lướt sóng",
  "tennis racket": "vợt tennis",
  bottle: "chai",
  "wine glass": "ly rượu",
  cup: "cốc",
  fork: "nĩa",
  knife: "dao",
  spoon: "thìa",
  bowl: "bát",
  banana: "chuối",
  apple: "táo",
  sandwich: "bánh sandwich",
  orange: "cam",
  broccoli: "bông cải",
  carrot: "cà rốt",
  "hot dog": "xúc xích",
  pizza: "pizza",
  donut: "bánh donut",
  cake: "bánh ngọt",
  chair: "ghế",
  couch: "ghế sofa",
  "potted plant": "chậu cây",
  bed: "giường",
  "dining table": "bàn ăn",
  toilet: "bồn cầu",
  tv: "tivi",
  laptop: "máy tính xách tay",
  mouse: "chuột máy tính",
  remote: "điều khiển",
  keyboard: "bàn phím",
  "cell phone": "điện thoại",
  microwave: "lò vi sóng",
  oven: "lò nướng",
  toaster: "lò nướng bánh",
  sink: "bồn rửa",
  refrigerator: "tủ lạnh",
  book: "sách",
  clock: "đồng hồ",
  vase: "bình hoa",
  scissors: "kéo",
  "teddy bear": "gấu bông",
  "hair drier": "máy sấy tóc",
  toothbrush: "bàn chải đánh răng",
};

// Cảnh báo cao: vật thể có nguy cơ va chạm / nguy hiểm
export const HIGH_PRIORITY = new Set([
  "person",
  "bicycle",
  "car",
  "motorcycle",
  "bus",
  "truck",
  "train",
  "stop sign",
  "traffic light",
  "dog",
  "horse",
  "cow",
]);

export function toVietnamese(label: string): string {
  return COCO_VI[label] ?? label;
}
